### ISSUE TITLE
email validation class does not work 

### ISSUE THREAD

**Issue by blueamerican** [svewap/formhandler_cleverreach#3]
TYPO3 7.6.10
formhandler_cleverreach from github

from doubleOptIn setup.txt

```
validators {
        1 {
            class = Validator\Default
            config {
                fieldConf {
                    firstname {
                        errorCheck.1 = required
                        errorCheck.2 = maxLength
                        errorCheck.2.value = 50
                    }
                    lastname {
                        errorCheck.1 = required
                        errorCheck.2 = maxLength
                        errorCheck.2.value = 50
                    }
                    email {
                        errorCheck.1 = required
                        errorCheck.2 = email
                        errorCheck.3.class = WapplerSystems\FormhandlerCleverreach\Formhandler\ErrorCheck\CleverReachEmailOptin
                        errorCheck.3.config < plugin.tx_formhandlercleverreach.config
                    }

                }
            }
        }
    }
```

the row errorCheck.3.class = WapplerSy..
does not work for me. the class is not invoked during the validation.

i don't know why

**Comment by svewap** [comment]
I wrote the validators new. Please test.

**Comment by blueamerican** [comment]
i tested the new version.

now the classes are invoked, but i do not get the error message:
"email already registered".

in this case i get the normal success message "Vielen Dank für Ihre Anmeldung. Wir haben an Ihre Email-Adresse einen Link gesendet, mit dem Sie die Anmeldung bestätigen können."
![cleverreach1](https://cloud.githubusercontent.com/assets/5647051/17267881/c9fe0614-5616-11e6-86bb-ad08bf92753e.jpg)

for details see attached screen

**Comment by blueamerican** [comment]
in der Klasse CleverReachEmailOptin ind der Funktion check ist
$this->subscriber_active nicht bekannt oder gesetzt

**Comment by blueamerican** [comment]
wenn ich in CleverReachEmail in der Funktion check das hier ersetze:

$this->subscriber_active = ($return->data->activated == 1);

mit 
if ($return->data->activated) {
            $this->subscriber_active = 1;
        }

geht es. Du kannst ja mal schauen ob das so stimmt

**Comment by svewap** [comment]
Die Bedingung müsste eigentlich
$this->subscriber_active = ($return->data->active != 0);
heißen und befindet sich in der CleverReachEmail Klasse und wird dort auch ausgeführt. Allerdings ist der Rückgabewert von CleverReach manchmal nicht eindeutig. Mal ist active leer (was eigentlich nicht sein dürfte) und mal mit einem Integer belegt.
