### ISSUE TITLE
Formhandler-less version planned?

### ISSUE THREAD

**Issue by SicorDev** [svewap/formhandler_cleverreach#4]
Hi, just a quick question: 

Since [formhandler](https://typo3.org/extensions/repository/view/formhandler) is no longer maintained, are you planning a switch to powermail/form in the near future?

Greetings,
Manuel

**Comment by svewap** [comment]
Hi! The problem is, that there is no order because I don't have some customer using cleverreach with cleverreach anymore. Maybe I will write a complete new version if I will update my own website to TYPO3 V8. I think I will use the new forms extension of TYPO3 core.
